server:
  port: 8080

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/framework?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 1234

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #스프링 부트 스타터를 통해 p6spy를 추가했다면 url에 p6spy를 포함하지 않아도 된다.
#    url: jdbc:p6spy:mysql://localhost:3306/framework?characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/framework?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

#logging:
#  level:
#    p6spy: info

springdoc:
 swagger-ui:
    path: /bluechip/api/docs/admin
    operationsSorter: method
    mainDescription: |
      **<  SWAGGER-UI 사용자 메뉴얼 >**  
      
      **STEP 1 --------------------------------------------------------------------------------------------**  
      
      [USER] Account 클래스의 **로그인 API**를 통해 로그인 후 Access/Refresh Token 을 발급받는다.  
      
      **STEP 2 --------------------------------------------------------------------------------------------**           
      
      우측 하단의 **Authorize**에 Access Token 을 등록한다 (전역 헤더 설정).   
      
      **STEP 3 --------------------------------------------------------------------------------------------**    
      
      Access Token 의 전역 헤더 설정을 완료 했다면 API에 접근 할 수 있다.  
      
      **STEP 4 --------------------------------------------------------------------------------------------**   
      
      API 사용시 **403 Forbidden**이 발생한다면 Access Token 이 만료된 것으로  
      [AUTH] 인증/인가 클래스의 Token Refresh API를 통해 Access Token 을 재발급 받는다.  
      토큰 재발급 후 STEP 2,3 과정을 수행한다.
      
    
      











